{"is_success": "Fail", "type": "weather", "std_day": "20200303", "params": {"ServiceKey": "lWLaCFJasDo6vpnFordk0ZVBBDk0eu0yL+KUjEF56K+w78w4lsKg7BJANNWeWbL2mzl72Q4LfFyIygL5qCGGkA==", "numOfRows": "30", "dataType": "JSON", "dataCd": "ASOS", "dateCd": "HR", "startDt": "20200303", "startHh": "00", "endDt": "20200303", "endHh": "23", "stnIds": "108"}, "err_msg": "HTTPConnectionPool(host='apis.data.go.kr', port=80): Max retries exceeded with url: /1360000/AsosHourlyInfoService/getWthrDataList?ServiceKey=lWLaCFJasDo6vpnFordk0ZVBBDk0eu0yL%2BKUjEF56K%2Bw78w4lsKg7BJANNWeWbL2mzl72Q4LfFyIygL5qCGGkA%3D%3D&numOfRows=30&dataType=JSON&dataCd=ASOS&dateCd=HR&startDt=20200303&startHh=00&endDt=20200303&endHh=23&stnIds=108 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6efbe55190>: Failed to establish a new connection: [Errno 111] Connection refused'))"}
